# Generated by Django 4.2.13 on 2024-05-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
